import { useEffect, useState } from 'react';
import { formatPrice, getAdminStats, getAllSubscriptions, AdminStats, Subscription, SubscriptionStatus } from '../services/api';
import { getCurrentUser } from '../services/auth';

const STATUS_LABELS: Record<SubscriptionStatus, string> = { active: 'Active', paused: 'Paused', cancelled: 'Cancelled' };
export default function AdminDashboardPage() {
  const [stats, setStats] = useState<AdminStats | null>(null); const [subs, setSubs] = useState<Subscription[]>([]); const [loading, setLoading] = useState(true); const user = getCurrentUser();
  useEffect(() => { Promise.all([getAdminStats(), getAllSubscriptions()]).then(([currentStats, subscriptions]) => { setStats(currentStats); setSubs(subscriptions || []); }).finally(() => setLoading(false)); }, []);
  if (loading) return <main className="page"><div className="loading"><div className="spinner" /><span>Loading dashboard…</span></div></main>;
  const recentSubs = [...subs].slice(0, 10);
  return <main className="page"><header className="page-header"><h1 className="page-title">Admin <span className="gradient-text">Dashboard</span></h1><p className="page-subtitle">Welcome back, {user?.name} — here's your platform overview</p></header><div className="grid-3 animate-up" style={{ marginBottom: '3rem' }}><div className="stat-card"><div className="stat-icon">👥</div><div className="stat-value">{stats?.total_customers ?? 0}</div><div className="stat-label">Total Customers</div></div><div className="stat-card"><div className="stat-icon">✅</div><div className="stat-value">{stats?.active_subscriptions ?? 0}</div><div className="stat-label">Active Subscriptions</div></div><div className="stat-card"><div className="stat-icon">🍽️</div><div className="stat-value">{stats?.total_meal_plans ?? 0}</div><div className="stat-label">Meal Plans</div></div></div><div className="header-row"><h2 style={{ fontSize: '1.2rem', fontWeight: 700 }}>Recent Subscriptions</h2><span style={{ color: 'var(--text-muted)', fontSize: '0.875rem' }}>{subs.length} total</span></div>{subs.length === 0 ? <div className="empty-state"><div className="empty-icon">📊</div><h3 className="empty-title">No subscriptions yet</h3><p className="empty-desc">Subscriptions will appear here once customers sign up.</p></div> : <div className="table-wrap animate-up"><table className="table" aria-label="Recent subscriptions"><thead><tr><th>#</th><th>Customer ID</th><th>Meal Plan</th><th>Price (INR)</th><th>Status</th><th>Subscribed</th></tr></thead><tbody>{recentSubs.map((sub) => <tr key={sub.id}><td style={{ color: 'var(--text-muted)' }}>{sub.id}</td><td>User #{sub.customer_id}</td><td style={{ fontWeight: 600 }}>{sub.meal_plan?.name ?? `Plan #${sub.meal_plan_id}`}</td><td>{formatPrice(sub.meal_plan?.price ?? 0)}</td><td><span className={`badge badge-${sub.status}`}>{STATUS_LABELS[sub.status]}</span></td><td style={{ color: 'var(--text-secondary)' }}>{new Date(sub.created_at).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' })}</td></tr>)}</tbody></table></div>}</main>;
}