import { useCallback, useEffect, useState, ChangeEvent, FormEvent } from 'react';
import { createMealPlan, deleteMealPlan, formatPrice, getMealPlans, MealPlan, MealPlanInput, updateMealPlan } from '../services/api';

type MealPlanForm = Omit<MealPlanInput, 'price'> & { price: number | string };
const EMPTY_FORM: MealPlanForm = { name: '', description: '', price: '', status: 'active', meal_type: 'dinner' };
interface Message { type: 'error' | 'success'; text: string; }

export default function AdminMealPlansPage() {
  const [plans, setPlans] = useState<MealPlan[]>([]); const [loading, setLoading] = useState(true); const [modal, setModal] = useState<'create' | 'edit' | null>(null); const [editing, setEditing] = useState<MealPlan | null>(null); const [form, setForm] = useState(EMPTY_FORM); const [saving, setSaving] = useState(false); const [deleting, setDeleting] = useState<number | null>(null); const [message, setMessage] = useState<Message | null>(null);
  const load = useCallback(() => { setLoading(true); getMealPlans().then((data) => setPlans(data || [])).catch((err: unknown) => setMessage({ type: 'error', text: err instanceof Error ? err.message : 'Unable to load meal plans' })).finally(() => setLoading(false)); }, []);
  useEffect(load, [load]);
  const set = (key: keyof typeof form) => (event: ChangeEvent<HTMLInputElement | HTMLSelectElement>) => setForm((current) => ({ ...current, [key]: event.target.value }));
  const openCreate = () => { setForm(EMPTY_FORM); setEditing(null); setModal('create'); }; const openEdit = (plan: MealPlan) => { setForm({ name: plan.name, description: plan.description, price: String(plan.price), status: plan.status, meal_type: plan.meal_type || 'dinner' }); setEditing(plan); setModal('edit'); }; const closeModal = () => { setModal(null); setEditing(null); };
  const handleSave = async (event: FormEvent) => { event.preventDefault(); setMessage(null); setSaving(true); const payload: MealPlanInput = { ...form, price: Number.parseFloat(String(form.price)) }; try { if (modal === 'create') { const created = await createMealPlan(payload); setPlans((current) => [created, ...current]); setMessage({ type: 'success', text: `"${created.name}" created successfully.` }); } else if (editing) { const updated = await updateMealPlan(editing.id, payload); setPlans((current) => current.map((plan) => plan.id === editing.id ? updated : plan)); setMessage({ type: 'success', text: `"${updated.name}" updated.` }); } closeModal(); } catch (err) { setMessage({ type: 'error', text: err instanceof Error ? err.message : 'Unable to save meal plan' }); } finally { setSaving(false); } };
  const handleDelete = async (plan: MealPlan) => { if (!window.confirm(`Delete "${plan.name}"? This cannot be undone.`)) return; setDeleting(plan.id); setMessage(null); try { await deleteMealPlan(plan.id); setPlans((current) => current.filter((item) => item.id !== plan.id)); setMessage({ type: 'success', text: `"${plan.name}" deleted.` }); } catch (err) { setMessage({ type: 'error', text: err instanceof Error ? err.message : 'Unable to delete meal plan' }); } finally { setDeleting(null); } };
  return <main className="page"><div className="header-row"><div><h1 className="page-title">Manage <span className="gradient-text">Meal Plans</span></h1><p className="page-subtitle">{plans.length} plan{plans.length !== 1 ? 's' : ''} total</p></div><button id="create-plan-btn" className="btn btn-primary" onClick={openCreate}>+ New Plan</button></div>
    {message && <div className={`alert alert-${message.type}`} role="alert">{message.text}</div>}{loading ? <div className="loading"><div className="spinner" /><span>Loading…</span></div> : plans.length === 0 ? <div className="empty-state"><div className="empty-icon">📋</div><h2 className="empty-title">No meal plans yet</h2><p className="empty-desc">Create your first plan to get started.</p></div> : <div className="table-wrap animate-up"><table className="table" aria-label="Meal plans"><thead><tr><th>Name</th><th>Description</th><th>Price (INR)</th><th>Status</th><th>Actions</th></tr></thead><tbody>{plans.map((plan) => <tr key={plan.id}><td style={{ fontWeight: 600 }}>{plan.name}</td><td style={{ color: 'var(--text-secondary)', maxWidth: '280px' }}>{plan.description?.slice(0, 80)}{plan.description?.length > 80 ? '…' : ''}</td><td style={{ fontWeight: 700 }}>{formatPrice(plan.price)}</td><td><span className={`badge badge-${plan.status}`}>{plan.status}</span></td><td><div className="td-actions"><button id={`edit-plan-${plan.id}`} className="btn btn-secondary btn-sm" onClick={() => openEdit(plan)}>✎ Edit</button><button id={`delete-plan-${plan.id}`} className="btn btn-danger btn-sm" onClick={() => handleDelete(plan)} disabled={deleting === plan.id}>{deleting === plan.id ? '…' : '✕ Delete'}</button></div></td></tr>)}</tbody></table></div>}
    {modal && <div className="modal-overlay" role="dialog" aria-modal="true" aria-labelledby="modal-title"><div className="modal"><h2 id="modal-title" className="modal-title">{modal === 'create' ? '✦ New Meal Plan' : `Edit "${editing?.name}"`}</h2><form onSubmit={handleSave}><div className="form-group"><label className="form-label" htmlFor="mp-name">Plan name</label><input id="mp-name" type="text" className="form-input" placeholder="e.g. Premium Chef" value={form.name} onChange={set('name')} required /></div><div className="form-group"><label className="form-label" htmlFor="mp-desc">Description</label><input id="mp-desc" type="text" className="form-input" placeholder="Brief description of the plan" value={form.description} onChange={set('description')} /></div><div className="form-group"><label className="form-label" htmlFor="mp-price">Weekly price (INR)</label><input id="mp-price" type="number" step="1" min="0" className="form-input" placeholder="299" value={form.price} onChange={set('price')} required /></div><div className="form-group"><label className="form-label" htmlFor="mp-type">Meal type</label><select id="mp-type" className="form-input" value={form.meal_type} onChange={set('meal_type')}><option value="breakfast">Breakfast</option><option value="lunch">Lunch</option><option value="dinner">Dinner</option></select></div><div className="form-group"><label className="form-label" htmlFor="mp-status">Status</label><select id="mp-status" className="form-input" value={form.status} onChange={set('status')}><option value="active">Active</option><option value="inactive">Inactive</option></select></div><div className="modal-footer"><button type="button" className="btn btn-secondary" onClick={closeModal}>Cancel</button><button id="save-plan-btn" type="submit" className="btn btn-primary" disabled={saving}>{saving ? <><span className="spinner" /> Saving…</> : modal === 'create' ? 'Create Plan' : 'Save Changes'}</button></div></form></div></div>}
  </main>;
}