import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { formatPrice, getMySubscriptions, Subscription, SubscriptionStatus, updateSubscriptionStatus } from '../services/api';

const STATUS_LABELS: Record<SubscriptionStatus, string> = { active: 'Active', paused: 'Paused', cancelled: 'Cancelled' };
interface Message { type: 'error' | 'success'; text: string; }

export default function SubscriptionDashboardPage() {
  const [subs, setSubs] = useState<Subscription[]>([]); const [loading, setLoading] = useState(true); const [updating, setUpdating] = useState<number | null>(null); const [message, setMessage] = useState<Message | null>(null);
  const load = () => { setLoading(true); getMySubscriptions().then((data) => setSubs(data || [])).catch((err: unknown) => setMessage({ type: 'error', text: err instanceof Error ? err.message : 'Unable to load subscriptions' })).finally(() => setLoading(false)); };
  useEffect(load, []);
  const changeStatus = async (id: number, status: SubscriptionStatus) => { setMessage(null); setUpdating(id); try { await updateSubscriptionStatus(id, status); setSubs((previous) => previous.map((sub) => sub.id === id ? { ...sub, status } : sub)); setMessage({ type: 'success', text: `Subscription ${STATUS_LABELS[status].toLowerCase()}.` }); } catch (err) { setMessage({ type: 'error', text: err instanceof Error ? err.message : 'Unable to update subscription' }); } finally { setUpdating(null); } };
  const active = subs.filter((sub) => sub.status === 'active').length;
  return <main className="page"><header className="page-header"><h1 className="page-title">My <span className="gradient-text">Subscriptions</span></h1><p className="page-subtitle">{subs.length > 0 ? `${active} active subscription${active !== 1 ? 's' : ''} · manage them below` : 'Manage and track your meal plan subscriptions'}</p></header>
    {message && <div className={`alert alert-${message.type}`} role="alert">{message.text}</div>}{loading ? <div className="loading"><div className="spinner" /><span>Loading subscriptions…</span></div> : subs.length === 0 ? <div className="empty-state"><div className="empty-icon">📭</div><h2 className="empty-title">No subscriptions yet</h2><p className="empty-desc"><Link to="/" className="link">Browse our meal plans</Link> and subscribe to get started.</p></div> : <div style={{ display: 'flex', flexDirection: 'column', gap: '1rem' }}>{subs.map((sub, i) => <div key={sub.id} className="sub-card animate-up" style={{ animationDelay: `${i * 0.06}s` }}><div className="sub-info"><div style={{ display: 'flex', alignItems: 'center', gap: '0.75rem', marginBottom: '0.25rem' }}><h2 className="sub-name">{sub.meal_plan?.name ?? `Plan #${sub.meal_plan_id}`}</h2><span className={`badge badge-${sub.status}`}>{STATUS_LABELS[sub.status]}</span></div><p className="sub-price">{formatPrice(sub.meal_plan?.price ?? 0)} / week{sub.meal_plan?.description && <span style={{ color: 'var(--text-muted)', marginLeft: '0.5rem' }}>· {sub.meal_plan.description.slice(0, 60)}…</span>}</p></div><div className="sub-actions">{sub.status === 'active' && <><button id={`pause-btn-${sub.id}`} className="btn btn-warning btn-sm" onClick={() => changeStatus(sub.id, 'paused')} disabled={updating === sub.id}>{updating === sub.id ? '…' : '⏸ Pause'}</button><button id={`cancel-btn-${sub.id}`} className="btn btn-danger btn-sm" onClick={() => changeStatus(sub.id, 'cancelled')} disabled={updating === sub.id}>{updating === sub.id ? '…' : '✕ Cancel'}</button></>}{sub.status === 'paused' && <><button id={`resume-btn-${sub.id}`} className="btn btn-success btn-sm" onClick={() => changeStatus(sub.id, 'active')} disabled={updating === sub.id}>{updating === sub.id ? '…' : '▶ Resume'}</button><button id={`cancel-paused-btn-${sub.id}`} className="btn btn-danger btn-sm" onClick={() => changeStatus(sub.id, 'cancelled')} disabled={updating === sub.id}>{updating === sub.id ? '…' : '✕ Cancel'}</button></>}{sub.status === 'cancelled' && <button id={`reactivate-btn-${sub.id}`} className="btn btn-ghost btn-sm" onClick={() => changeStatus(sub.id, 'active')} disabled={updating === sub.id}>{updating === sub.id ? '…' : '↺ Reactivate'}</button>}</div></div>)}</div>}
  </main>;
}